name: instacart_api
description: InstaCart API client
version: 0.0.1+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  dio: ^4.0.6
  fpdart: ^0.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  package_info_plus: ^1.4.2

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1
  pretty_dio_logger: ^1.2.0-beta-1